// Generated by CoffeeScript 1.10.0
var config, engine, nextScene, scenes;

config = Config.get();

Persist.PREFIX = 'ce.tests';

Persist["default"]('lastTest', 0);

config.fillWindow();

engine = new Engine3D();

scenes = new CyclicArray([new BasicTest(), new ShaderTest(), new AnimationTest()]);

nextScene = function() {
  engine.initScene(scenes.next());
  return Persist.set('lastTest', scenes.index);
};

Engine3D.scenify(engine, function() {
  scenes.index = Persist.get('lastTest');
  return engine.initScene(scenes.get());
});

engine.render();
