// Generated by CoffeeScript 1.10.0
var TestScene,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

TestScene = (function(superClass) {
  extend(TestScene, superClass);

  function TestScene() {
    return TestScene.__super__.constructor.apply(this, arguments);
  }

  TestScene.prototype.init = function() {
    Helper.orbitControls(engine);
    return this.testInfo();
  };

  TestScene.prototype.testInfo = function() {
    return console.log('You can add test info by overriding testInfo() method in teh scene');
  };

  TestScene.prototype.uninit = function() {
    TestScene.__super__.uninit.call(this);
    if (this.controls != null) {
      this.controls.enabled = false;
    }
    engine.camera.position.set(0, 6.123233995736766e-16, 10);
    return engine.camera.lookAt(0, 0, 0);
  };

  return TestScene;

})(BaseScene);
