// Generated by CoffeeScript 1.10.0
var BasicTest,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

BasicTest = (function(superClass) {
  extend(BasicTest, superClass);

  function BasicTest() {
    return BasicTest.__super__.constructor.apply(this, arguments);
  }

  BasicTest.prototype.init = function() {
    BasicTest.__super__.init.call(this);
    this.cube = Helper.cube({
      size: 1,
      material: 'MeshPhongMaterial'
    });
    this.scene.add(this.cube);
    this.scene.add(Helper.ambientLight());
    this.scene.add(Helper.ambientLight());
    return this.scene.add(Helper.ambientLight());
  };

  BasicTest.prototype.tick = function(tpf) {
    this.cube.rotation.z += 1 * tpf;
    return this.cube.rotation.y += 1 * tpf;
  };

  BasicTest.prototype.doMouseEvent = function(event, raycaster) {};

  BasicTest.prototype.doKeyboardEvent = function(event) {};

  return BasicTest;

})(TestScene);
