// Generated by CoffeeScript 1.10.0
var LightTest,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

LightTest = (function(superClass) {
  extend(LightTest, superClass);

  function LightTest() {
    return LightTest.__super__.constructor.apply(this, arguments);
  }

  LightTest.prototype.init = function() {
    LightTest.__super__.init.call(this);
    this.scene.add(Helper.ambientLight());
    this.scene.add(Helper.ambientLight());
    return this.scene.add(Helper.ambientLight());
  };

  LightTest.prototype.tick = function(tpf) {};

  LightTest.prototype.doMouseEvent = function(event, raycaster) {};

  LightTest.prototype.doKeyboardEvent = function(event) {};

  return LightTest;

})(TestScene);
