// Generated by CoffeeScript 1.10.0
var ShaderTest,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ShaderTest = (function(superClass) {
  extend(ShaderTest, superClass);

  function ShaderTest() {
    return ShaderTest.__super__.constructor.apply(this, arguments);
  }

  ShaderTest.prototype.init = function() {
    ShaderTest.__super__.init.call(this);
    this.shader = Helper.sampleShader();
    this.scene.add(this.shader);
    this.scene.add(Helper.ambientLight());
    this.scene.add(Helper.ambientLight());
    return this.scene.add(Helper.ambientLight());
  };

  ShaderTest.prototype.tick = function(tpf) {
    return this.shader.shaderSrc.uniforms.time.value += tpf * 10;
  };

  ShaderTest.prototype.doMouseEvent = function(event, raycaster) {};

  ShaderTest.prototype.doKeyboardEvent = function(event) {};

  return ShaderTest;

})(TestScene);
